--- 
abstract: Transparent BigNumber support for Perl
author: Tels <nospam-abuse@bloodgate.com>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.65
installdirs: perl
license: gpl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: bignum
no_index: 
  directory: 
    - inc
    - t
requires: 
  Math::BigInt: 1.82
  Math::BigRat: 0.18
  perl: 5.6.2
version: 0.20
